***Custom Feature Transformation using apply()<br>
Context: Real ML requires custom logic transformation.<br>
Dataset: Titanic***

**Create age_group: Child / Adult / Senior**

In [1]:
import numpy as np
import seaborn as sns
import pandas as pd

titanic_df = sns.load_dataset("titanic")
titanic_df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [23]:
def get_age_group(age):
    if age < 12:
        return 'Child'
    elif age <= 30:
        return 'Adult'
    elif age > 30:
        return 'Senior'

titanic_df['age_group'] = titanic_df['age'].apply(get_age_group)
titanic_df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_group
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,Adult
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,Senior
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,Adult
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,Senior
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,Senior
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,Adult
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,Adult
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,None
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,Adult
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,Senior

**Compute survival rate per group**

In [24]:
survival_age_group = titanic_df.groupby('age_group')['survived'].mean()
print(f"Survival of age group adult {survival_age_group.loc['Adult']:.2%}")
print(f"Survival of age group Child {survival_age_group.loc['Child']:.2%}")
print(f"Survival of age group Senior {survival_age_group.loc['Senior']:.2%}")

Survival of age group adult 37.24%
Survival of age group Child 57.35%
Survival of age group Senior 40.66%

**Interpret: Which segment has highest survival likelihood**

In [28]:
highest_survival =titanic_df.groupby('age_group')['survived'].mean().sort_values(ascending=False)
highest_survival[0:1]

age_group
Child    0.573529
Name: survived, dtype: float64