***End-to-End ML Preprocessing Pipeline (Titanic)<br>
Context: Prepare dataset for ML model training***

**Load dataset**

In [40]:
import seaborn as sns
import pandas as pd
import numpy as np

titanic_df = sns.load_dataset("titanic")
titanic_df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

**Handle missing values**

In [21]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

As shown in info **age** has **177** and **embark_town**, **embarked** has few missing value.<br>
that needs to be handled.

In [22]:
titanic_df['age'] = titanic_df['age'].fillna(titanic_df['age'].median())
titanic_df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,28.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [23]:
age_null_value_count = titanic_df['age'].isna().sum()
print(f"titanic age null value count {age_null_value_count}")

titanic age null value count 0

In [29]:
titanic_df.dropna(subset=['embark_town'], inplace=True)
titanic_df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,28.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [28]:
embarked_null_value_count = titanic_df['embark_town'].isna().sum()
print(f"titanic age null value count {embarked_null_value_count}")

titanic age null value count 0

In [34]:
titanic_df.drop(columns=['deck'], inplace=True)
titanic_df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,28.0,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

**Encode categorical variables (sex, embarked)**

In [44]:
titanic_df['sex'] = titanic_df['sex'].map({'male': 0, 'female': 1})
titanic_df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,1.0,Third,man,True,NaN,Southampton,no,False
1,1,1,1,38.0,1,0,71.2833,1.0,First,woman,False,C,Cherbourg,yes,False
2,1,3,1,26.0,0,0,7.9250,1.0,Third,woman,False,NaN,Southampton,yes,True
3,1,1,1,35.0,1,0,53.1000,1.0,First,woman,False,C,Southampton,yes,False
4,0,3,0,35.0,0,0,8.0500,1.0,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,27.0,0,0,13.0000,1.0,Second,man,True,NaN,Southampton,no,True
887,1,1,1,19.0,0,0,30.0000,1.0,First,woman,False,B,Southampton,yes,True
888,0,3,1,NaN,1,2,23.4500,1.0,Third,woman,False,NaN,Southampton,no,False
889,1,1,0,26.0,0,0,30.0000,1.0,First,man,True,C,Cherbourg,yes,True
890,0,3,0,32.0,0,0,7.7500,3.0,Third,man,True,NaN,Queenstown,no,True

**Getting embarked column available unique categorical data that will be used to encode with their corresponding numerical data**

In [36]:
titanic_df['embarked'].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [43]:
titanic_df['embarked'] = titanic_df['embarked'].map({'S': 1,'C': 1 ,'Q': 3})
titanic_df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,1.0,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,1.0,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,1.0,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,1.0,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,1.0,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,1.0,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,1.0,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,1.0,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,1.0,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,3.0,Third,man,True,NaN,Queenstown,no,True

**Normalize numerical features<br>**
**Here we have 2 feature that can be normalize that is Age and fare**

In [47]:
titanic_df['age']  = (titanic_df['age'] - titanic_df['age'].min())/(titanic_df['age'].max() - titanic_df['age'].min())
titanic_df['fare']  = (titanic_df['fare'] - titanic_df['fare'].min())/(titanic_df['fare'].max() - titanic_df['fare'].min())
titanic_df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,0,0.271174,1,0,0.014151,1.0,Third,man,True,NaN,Southampton,no,False
1,1,1,1,0.472229,1,0,0.139136,1.0,First,woman,False,C,Cherbourg,yes,False
2,1,3,1,0.321438,0,0,0.015469,1.0,Third,woman,False,NaN,Southampton,yes,True
3,1,1,1,0.434531,1,0,0.103644,1.0,First,woman,False,C,Southampton,yes,False
4,0,3,0,0.434531,0,0,0.015713,1.0,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,0.334004,0,0,0.025374,1.0,Second,man,True,NaN,Southampton,no,True
887,1,1,1,0.233476,0,0,0.058556,1.0,First,woman,False,B,Southampton,yes,True
888,0,3,1,NaN,1,2,0.045771,1.0,Third,woman,False,NaN,Southampton,no,False
889,1,1,0,0.321438,0,0,0.058556,1.0,First,man,True,C,Cherbourg,yes,True
890,0,3,0,0.396833,0,0,0.015127,3.0,Third,man,True,NaN,Queenstown,no,True

**Convert to NumPy array<br>**
**converted only the feature that has numerical data**

In [51]:
features = ['survived','pclass','sex','age','sibsp','parch','fare','embarked']
titanic_df_array = titanic_df[features].to_numpy()
titanic_df_array[0]

array([[0.        , 3.        , 0.        , ..., 0.        , 0.01415106,
        1.        ],
       [1.        , 1.        , 1.        , ..., 0.        , 0.13913574,
        1.        ],
       [1.        , 3.        , 1.        , ..., 0.        , 0.01546857,
        1.        ],
       ...,
       [0.        , 3.        , 1.        , ..., 2.        , 0.04577135,
        1.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.0585561 ,
        1.        ],
       [0.        , 3.        , 0.        , ..., 0.        , 0.01512699,
        3.        ]])