***Q2. Data Selection for Model Input<br>
Context: Models are trained on selective features, not full raw data.***

***Dataset: Iris***

In [3]:
import seaborn as sns

_iris_df = sns.load_dataset("iris")
_iris_df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

___Extract: First 100 samples Only last 2 features___

In [20]:
first_100_feature_df = _iris_df.loc[:,['petal_width', 'species']].head(100)
first_100_feature_df

    petal_width     species
0           0.2      setosa
1           0.2      setosa
2           0.2      setosa
3           0.2      setosa
4           0.2      setosa
..          ...         ...
95          1.2  versicolor
96          1.3  versicolor
97          1.3  versicolor
98          1.1  versicolor
99          1.3  versicolor

[100 rows x 2 columns]

***Use boolean masking: Select samples where petal length is greater than dataset mean***

In [43]:
result  = _iris_df.loc[_iris_df['petal_length'] > _iris_df['petal_length'].mean()]
result

     sepal_length  sepal_width  petal_length  petal_width     species
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
53            5.5          2.3           4.0          1.3  versicolor
54            6.5          2.8           4.6          1.5  versicolor
..            ...          ...           ...          ...         ...
145           6.7          3.0           5.2          2.3   virginica
146           6.3          2.5           5.0          1.9   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica
149           5.9          3.0           5.1          1.8   virginica

[93 rows x 5 columns]

**Count selected samples**

In [50]:
result.count()

sepal_length    93
sepal_width     93
petal_length    93
petal_width     93
species         93
dtype: int64

**Explain how this relates to feature-based filtering in ML**

___?????___