***Group-Based Insights (Customer Segmentation Logic)<br>
Context: ML models often depend on aggregated patterns.<br>
Dataset: Tips***

**Compute: Average tip by day Total bill by gender**

In [3]:
import seaborn as sns
import numpy as np
import pandas as pd

tips_df = sns.load_dataset("tips")
tips_df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

**Compute: Average tip by day Total bill by gender**

In [8]:
avg_tip = tips_df.groupby('day', observed=False)['tip'].mean()
print(f"Average tip by day {avg_tip}")

total_bill = tips_df.groupby('sex',observed=False)['total_bill'].sum()
print(f"Average tip by day {total_bill}")

Average tip by day day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64
Average tip by day sex
Male      3256.82
Female    1570.95
Name: total_bill, dtype: float64

**Create new feature: tip_percentage**

In [10]:
tips_df['tip_percentage'] = (tips_df['tip']/tips_df['total_bill'])*100
tips_df

     total_bill   tip     sex smoker   day    time  size  tip_percentage
0         16.99  1.01  Female     No   Sun  Dinner     2        5.944673
1         10.34  1.66    Male     No   Sun  Dinner     3       16.054159
2         21.01  3.50    Male     No   Sun  Dinner     3       16.658734
3         23.68  3.31    Male     No   Sun  Dinner     2       13.978041
4         24.59  3.61  Female     No   Sun  Dinner     4       14.680765
..          ...   ...     ...    ...   ...     ...   ...             ...
239       29.03  5.92    Male     No   Sat  Dinner     3       20.392697
240       27.18  2.00  Female    Yes   Sat  Dinner     2        7.358352
241       22.67  2.00    Male    Yes   Sat  Dinner     2        8.822232
242       17.82  1.75    Male     No   Sat  Dinner     2        9.820426
243       18.78  3.00  Female     No  Thur  Dinner     2       15.974441

[244 rows x 8 columns]

**dentify: Which day has highest tipping behavior**

In [14]:
tip_by_day = tips_df.groupby('day',observed=False)[['tip','tip_percentage']].mean()
result = tip_by_day['tip_percentage'].idxmax()
max_tip = tip_by_day['tip_percentage'].max()
print(f" On {result} has highest tip {max_tip}")

 On Fri has highest tip 16.991302873347887